### ISSUE TITLE
Fails to compile with asmjs-unknown-emscripten

### ISSUE THREAD

**Issue by LukasKalbertodt** [alexcrichton/backtrace-rs#18]
(strange, it's me again; hopefully this time my report has actually something to do with `backtrace`)

When compiling a project depending on `backtrace` with `--target asmjs-unknown-emscripten`, I get this error:

```
   Compiling backtrace-sys v0.1.4
     Running `/home/lukas/dev/plantex/target/release/build/backtrace-sys-4a333e150e37ba3b/build-script-build`
error: failed to run custom build command for `backtrace-sys v0.1.4`
process didn't exit successfully: `/home/lukas/dev/plantex/target/release/build/backtrace-sys-4a333e150e37ba3b/build-script-build` (exit code: 101)
--- stdout
OPT_LEVEL = Some("3")
PROFILE = Some("release")
TARGET = Some("asmjs-unknown-emscripten")
debug=false opt-level=3
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("asmjs-unknown-emscripten")
TARGET = Some("asmjs-unknown-emscripten")
HOST = Some("x86_64-unknown-linux-gnu")
CC_asmjs-unknown-emscripten = None
CC_asmjs_unknown_emscripten = None
TARGET_CC = None
CC = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("asmjs-unknown-emscripten")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_asmjs-unknown-emscripten = None
CFLAGS_asmjs_unknown_emscripten = None
TARGET_CFLAGS = None
CFLAGS = None
running: "/home/lukas/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.4/src/libbacktrace/configure" "--with-pic" "--disable-multilib" "--disable-shared" "--disable-host-shared" "--target=asmjs-unknown-emscripten" "--host=x86_64-unknown-linux-gnu"
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... 
--- stderr
configure: WARNING: If you wanted to set the --build type, don't use --host.
    If a cross compiler is detected then cross compile mode will be used.
Invalid configuration `asmjs-unknown-emscripten': system `emscripten' not recognized
configure: error: /bin/bash /home/lukas/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.4/src/libbacktrace/config.sub asmjs-unknown-emscripten failed
thread 'main' panicked at 'failed with: exit code: 1', /home/lukas/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.4/build.rs:63
stack backtrace:
   1:     0x55a4447ea81f - std::sys::backtrace::tracing::imp::write::h22f199c1dbb72ba2
   2:     0x55a4447f06bd - std::panicking::default_hook::{{closure}}::h9a389c462b6a22dd
   3:     0x55a4447ef652 - std::panicking::default_hook::h852b4223c1c00c59
   4:     0x55a4447efb98 - std::panicking::rust_panic_with_hook::hcd9d05f53fa0dafc
   5:     0x55a4447efa32 - std::panicking::begin_panic::hf6c488cee66e7f17
   6:     0x55a4447ef970 - std::panicking::begin_panic_fmt::hb0a7126ee57cdd27
   7:     0x55a4447dad69 - build_script_build::run::hd1d9cc3b7c1d4ef5
   8:     0x55a4447da469 - build_script_build::main::h4b7e86393e928de9
   9:     0x55a4447f8186 - __rust_maybe_catch_panic
  10:     0x55a4447eeed1 - std::rt::lang_start::h14cbded5fe3cd915
  11:     0x7f4ccd91e82f - __libc_start_main
  12:     0x55a4447d88e8 - _start
  13:                0x0 - <unknown>
```

Rust version:

```
rustc 1.14.0-nightly (a3bc191b5 2016-10-10)
binary: rustc
commit-hash: a3bc191b5f41df5143cc65084b13999896411817
commit-date: 2016-10-10
host: x86_64-unknown-linux-gnu
release: 1.14.0-nightly
```

If I shall provide more information, just tell me!

**Comment by alexcrichton** [comment]
Interesting! Should probably just disable this crate entirely for emscripten, I doubt it'd ever work.

**Comment by LukasKalbertodt** [comment]
I'm not sure if this is related, but when I use your fix to compile my project and try to link it with `emcc`, I get this:

```
[...]
error: unresolved symbol: backtrace_create_state
error: unresolved symbol: llvm_round_f32
error: unresolved symbol: llvm_cos_f32
error: unresolved symbol: backtrace_pcinfo
error: unresolved symbol: backtrace_syminfo
[...]
```

**Comment by alexcrichton** [comment]
Oh oops, I just pushed a new commit and maybe that'll help?

**Comment by LukasKalbertodt** [comment]
Thanks for the quick response, but the commit doesn't seem to fix the problem. Do we want to reopen this issue?

Instead of trying with this big project of mine, here is a "minimal example", so to speak. 

(1) `cargo new --bin test18 && cd test18`
(2) `Cargo.toml`:
```
[dependencies]
glium = { git = 'https://github.com/tomaka/glium' }

[replace]
"glutin:0.6.1" = { git = 'https://github.com/tomaka/glutin' }
"backtrace-sys:0.1.4" = { git = 'https://github.com/alexcrichton/backtrace-rs' }
```
(3) Copy the contents of [this file](https://github.com/tomaka/glium/blob/master/examples/tutorial-02.rs) into `main.rs`
(4) `cargo run --target asmjs-unknown-emscripten`

Results in:

```
error: linking with `emcc` failed: exit code: 1

[...]
warning: emitted code will contain very large numbers of local variables, which is bad for performance (build to JS with -O2 or above to avoid this - make sure to do so both on source files, and during 'linking')
error: unresolved symbol: backtrace_create_state
error: unresolved symbol: backtrace_pcinfo
error: unresolved symbol: backtrace_syminfo
Aborting compilation due to previous errors | undefined
Traceback (most recent call last):
[...]
```

**Comment by alexcrichton** [comment]
Ah you'll want to override the `backtrace` crate as well as the backtrace-sys crate, the patch when there as well I believe.

**Comment by LukasKalbertodt** [comment]
That did the trick! 

I just saw my first `glium`-triangle in a browser, so this issue is certainly resolved :wink: Thanks for the help!
